
import com.itextpdf.text.log.Logger;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Danuar Anardha
 */
public class FormCariBuku extends javax.swing.JFrame {
    Connection koneksiDB = Koneksi.getConnection();
    /**
     * Creates new form FormCariBuku
     */
    public FormCariBuku() {
        initComponents();
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent de) {
                warn();
            }

            public void removeUpdate(DocumentEvent de) {
                warn();
            }

            public void insertUpdate(DocumentEvent de) {
                warn();
            }

            public void warn() {
                try {
                    ResultSet hasil = koneksiDB.createStatement().executeQuery("select * from buku where id_buku like '%" + jTextField1.getText() + "%' or judul like '%" + jTextField1.getText() + "%' or pengarang like '%" + jTextField1.getText() + "%' or penerbit like '%" + jTextField1.getText() + "%'");
                    DefaultTableModel model = (DefaultTableModel) TBLCariBuku.getModel();
                    model.setRowCount(0);
                    while (hasil.next()) {
                        model.addRow(new String[]{hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10)});
                    }
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        kondisiAwal();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(FormCariBuku.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("PerpusCorps - Cari Buku");
    }

    private void kondisiAwal() {
        try {
            jTextField1.setText("");
            ResultSet hasil = koneksiDB.createStatement().executeQuery("select * from buku");
            DefaultTableModel model = (DefaultTableModel) TBLCariBuku.getModel();
            model.setRowCount(0);
            while (hasil.next()) {
                model.addRow(new String[]{hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6), hasil.getString(7), hasil.getString(8), hasil.getString(9), hasil.getString(10)});
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FormCariAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLCariBuku = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pencarian"));

        jTextField1.setText("jTextField1");

        jButton6.setText("PILIH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        TBLCariBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Pengarang", "Penerbit", "Kategori", "Tahun", "Stok", "Harga", "Gambar", "Tanggal Masuk"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLCariBuku.setAutoResizeMode(0);
        TBLCariBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLCariBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLCariBuku);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Urutkan"));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Judul", "Pengarang", "Penerbit", "Kategori", "Tahun", "Stok", "Harga", "Tanggal Masuk" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton5.setText("Urutkan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, 0, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cover Buku"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(411, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void TBLCariBukuMouseClicked(java.awt.event.MouseEvent evt) {                                         
        try {
            int row = TBLCariBuku.getSelectedRow();
            String to = TBLCariBuku.getModel().getValueAt(row, 0).toString();
            ResultSet hasil = koneksiDB.createStatement().executeQuery("select * from buku where id_buku ='" + to + "'");
            if (hasil.next()) {
                String id = hasil.getString(1);
                String gambar = hasil.getString(9);
                ImageIcon icon = new ImageIcon(gambar);
                Image image = icon.getImage();
                Image imgScale = image.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(imgScale);
                jLabel1.setIcon(scaledIcon);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (jComboBox2.getSelectedItem().toString().equals("ID") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 0, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("ID") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 0, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Judul") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 1, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Judul") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 1, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Pengarang") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 2, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Pengarang") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 2, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Penerbit") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 3, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Penerbit") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 3, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Kategori") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 4, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Kategori") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 4, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Tahun") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 5, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Tahun") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 5, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Stok") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 6, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Stok") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 6, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Harga") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 7, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Harga") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 7, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Tanggal Masuk") && jComboBox3.getSelectedItem().toString().equals("Ascending")) {
            QuickSortAsc.quickSortAsc(TBLCariBuku, 9, 0, TBLCariBuku.getRowCount() - 1);
        } else if (jComboBox2.getSelectedItem().toString().equals("Tanggal Masuk") && jComboBox3.getSelectedItem().toString().equals("Descending")) {
            QuickSortDesc.quickSortAsc(TBLCariBuku, 9, 0, TBLCariBuku.getRowCount() - 1);
        }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (TBLCariBuku.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Silikan pilih salah satu buku!");
        } else {
            int row = TBLCariBuku.getSelectedRow();
            String id = TBLCariBuku.getValueAt(row, 0).toString();
            String judul = TBLCariBuku.getValueAt(row, 1).toString();
            String pengarang = TBLCariBuku.getValueAt(row, 2).toString();
            String penerbit = TBLCariBuku.getValueAt(row, 3).toString();
            String stok = TBLCariBuku.getValueAt(row, 6).toString();
            FormPeminjaman.jComboBox2.setSelectedItem(id);
            FormPeminjaman.jTextField5.setText(judul);
            FormPeminjaman.jTextField6.setText(pengarang);
            FormPeminjaman.jTextField4.setText(penerbit);
            FormPeminjaman.jTextField12.setText(stok);
            this.dispose();
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCariBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable TBLCariBuku;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
